# Generated by Django 4.2.7 on 2024-03-19 08:40

import django.contrib.auth.models
from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.SoftDeleteManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
