# Generated by Django 4.2.7 on 2024-03-19 16:46

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.SoftDeleteManager()),
            ],
        ),
    ]
