# Generated by Django 4.2.7 on 2024-03-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('salary', models.PositiveIntegerField()),
                ('salary_from', models.PositiveIntegerField()),
                ('salary_until', models.PositiveIntegerField()),
            ],
        ),
    ]
