# Generated by Django 4.2.7 on 2024-03-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_from',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_until',
        ),
    ]
