# Generated by Django 4.2.7 on 2024-03-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0002_remove_vacancy_salary_from_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacancy',
            new_name='Job',
        ),
    ]
