# Generated by Django 4.2.7 on 2024-03-19 13:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FootballClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('logo', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp', 'gif'])])),
                ('is_favourite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(38)])),
                ('attendance', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=127)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(40)])),
                ('market_value', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('erkak', 'Man'), ('ayol', 'Woman'), ('ixtiyoriy', 'Not Mention')], default='ixtiyoriy', max_length=20)),
                ('position', models.CharField(choices=[('position', 'Position'), ('forward', 'Forward'), ('midfielder', 'Midfielder'), ('goalkeeper', 'Goalkeeper'), ('defender', 'Defender')], default='position', max_length=32)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_country', to='task4.country')),
                ('current_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_club', to='task4.footballclub')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_referee', to='task4.country')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('club_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_club', to='task4.footballclub')),
                ('club_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_club', to='task4.footballclub')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfering_player', to='task4.player')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=127)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_situation', to='task4.gamestatistic')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_situation', to='task4.player')),
            ],
        ),
        migrations.CreateModel(
            name='RefereeStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_games', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_statistic', to='task4.referee')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_played', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assist', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statistic', to='task4.player')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_leagues', to='task4.country')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_season', to='task4.season')),
            ],
        ),
        migrations.AddField(
            model_name='gamestatistic',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_game', to='task4.league'),
        ),
        migrations.AddField(
            model_name='gamestatistic',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_referee', to='task4.referee'),
        ),
        migrations.AddField(
            model_name='gamestatistic',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stadium', to='task4.stadium'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('club1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent1', to='task4.footballclub')),
                ('club2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent2', to='task4.footballclub')),
            ],
        ),
        migrations.AddField(
            model_name='footballclub',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_league', to='task4.league'),
        ),
    ]
